### ISSUE TITLE
Calibrating light sensor at 0 

### ISSUE THREAD

**Issue by emsark15** [adamspierer/climbing_assay#1]
Hi,

Recently I have had an issue with the light not registering upon execution in terminal. It registers the light source calibration at 0, even after rebooting the system. Is there a way for me to go in and reset the light source calibration? There is no ambient light to interfere with the brightness and there is nothing blocking the setup.

**Comment by adamspierer** [comment]
Hi @emsark15,

Try run`check_adc.py`in the Terminal. It should give a live output of what the sensor is reading. If there is no signal at 0, then there is a chance the circuit isn't quite right.

Let me know how that works, or send the Terminal output and pictures if I didn't understand correctly.

**Comment by emsark15** [comment]
That fixed it and it is reading signal. Thank you!
